--
-- CMS1 Data
--   CSV Filter
--

use cms1;

--
-- 認証
--
INSERT INTO `m_bldg_csv_filter` (`id`, `excel_column`, `physical`, `logical`) VALUES
(0, 'A', 'bldg_code', 'ビルコード'),
(1, 'B', 'name_ja_jp', 'ビル名'),
(2, 'C', 'name_en_us', 'ビル名(英語)'),
(3, 'D', 'name_kana', 'ビル名(カナ)'),
(4, 'E', 'area_code', 'オフィスビル一覧用エリアコード'),
(5, 'F', 'bldg_kubun', '新ビル区分'),
(6, 'G', 'pref_ja_jp', '都道府県名'),
(7, 'H', 'loca_ja_jp', '所在地'),
(8, 'I', 'pref_en_us', '都道府県名(英語)'),
(9, 'J', 'loca_en_us', '所在地(英語)'),
(10, 'K', 'srch_ward', '検索用エリア（区）'),
(11, 'L', 'srch_area', '検索用エリア'),
(12, 'M', 'use_route', '利用可能路線'),
(13, 'N', 'acc01_ja_jp', 'アクセス①'),
(14, 'O', 'acc02_ja_jp', 'アクセス②'),
(15, 'P', 'acc03_ja_jp', 'アクセス③'),
(16, 'Q', 'acc04_ja_jp', 'アクセス④'),
(17, 'R', 'acc05_ja_jp', 'アクセス⑤'),
(18, 'S', 'acc06_ja_jp', 'アクセス⑥'),
(19, 'T', 'acc01_en_us', 'アクセス(英語)①'),
(20, 'U', 'acc02_en_us', 'アクセス(英語)②'),
(21, 'V', 'acc03_en_us', 'アクセス(英語)③'),
(22, 'W', 'acc04_en_us', 'アクセス(英語)④'),
(23, 'X', 'acc05_en_us', 'アクセス(英語)⑤'),
(24, 'Y', 'acc06_en_us', 'アクセス(英語)⑥'),
(25, 'Z', 'appeal_ja_jp', 'アピール'),
(26, 'AA', 'appeal_en_us', 'アピール(英語)'),
(27, 'AB', 'dep_ja_jp', '担当部署名'),
(28, 'AC', 'dep_en_us', '担当部署名(英語)'),
(29, 'AD', 'person_ja_jp', '担当者名'),
(30, 'AE', 'person_en_us', '担当者名(英語)'),
(31, 'AF', 'person_tel', '担当者電話番号'),
(32, 'AG', 'person_email', '担当者メールアドレス'),
(33, 'AH', 'rain', '雨に濡れない'),
(34, 'AI', 'scale_ja_jp', '建物規模'),
(35, 'AJ', 'scale_en_us', '建物規模(英語)'),
(36, 'AK', '', '(空)'),
(37, 'AL', 'address_ja_jp', '所　　在　　地'),
(38, 'AM', 'completion_ja_jp', '竣　工　年　月'),
(39, 'AN', 'extension_ja_jp', '増　築　年　月'),
(40, 'AO', 'renovation_ja_jp', '最新リニューアル完了年月'),
(41, 'AP', 'floors_ja_jp', '規　　　　　模'),
(42, 'AQ', 'structure_ja_jp', '構　　　　　造'),
(43, 'AR', 'gross_area_ja_jp', '延　床　面　積'),
(44, 'AS', 'net_area_ja_jp', '有　効　面　積'),
(45, 'AT', 'site_area_ja_jp', '敷　地　面　積'),
(46, 'AU', 'bldg_height_ja_jp', '建　物　高　さ'),
(47, 'AV', 'architect_ja_jp', '設　計　監　理'),
(48, 'AW', 'elevators_ja_jp', 'エレベーター'),
(49, 'AX', 'hvac_system_ja_jp', '空　調　設　備'),
(50, 'AY', 'hvac_office_ja_jp', '基準冷暖房供給|&時間（事務所）'),
(51, 'AZ', 'hvac_retail_ja_jp', '基準冷暖房供給|&時間（店　舗）'),
(52, 'BA', '', '(空)'),
(53, 'BB', 'com_infra_ja_jp', '通信インフラ'),
(54, 'BC', 'office_lobby', 'オフィスロビー（セキュリティゲート）'),
(55, 'BD', 'emergency_power', '停電時のテナント専用部電力供給'),
(56, 'BE', 'open_hours_ja_jp', '開閉館時間'),
(57, 'BF', 'dining_facilities', '飲食施設充実'),
(58, 'BG', 'vip_correspondense', 'VIP対応'),
(59, 'BH', 'management_form', '管　理　形　態'),
(60, 'BI', 'security_system_ja_jp', '夜間入退館方法'),
(61, 'BJ', 'refresh_space_ja_jp', 'リフレッシュコーナー'),
(62, 'BK', 'parking_space_ja_jp', 'ガレージ収容台数'),
(63, 'BL', 'parking_open_ja_jp', 'ガレージ営業時間'),
(64, 'BM', 'comments_ja_jp', '特　記　事　項'),
(65, 'BN', '', '(空)'),
(66, 'BO', '', '(空)'),
(67, 'BP', '', '(空)'),
(68, 'BQ', '', '(空)'),
(69, 'BR', '', '(空)'),
(70, 'BS', '', '(空)'),
(71, 'BT', '', '(空)'),
(72, 'BU', '', '(空)'),
(73, 'BV', '', '(空)'),
(74, 'BW', '', '(空)'),
(75, 'BX', '', '(空)'),
(76, 'BY', '', '(空)'),
(77, 'BZ', '', '(空)'),
(78, 'CA', 'floor_area_ja_jp', '床　　面　　積'),
(79, 'CB', 'floor_load_ja_jp', '床　　荷　　重'),
(80, 'CC', 'small_area', '小規模面積あり'),
(81, 'CD', 'ceiling_height_ja_jp', '天　　井　　高'),
(82, 'CE', 'outlet_capacity_ja_jp', 'コンセント容量'),
(83, 'CF', 'raised_floor_ja_jp', 'ＯＡフロア'),
(84, 'CG', 'bathroom_ja_jp', 'ト　　イ　　レ'),
(85, 'CH', 'pantry_ja_jp', '給　　湯　　室'),
(86, 'CI', '', '(空)'),
(87, 'CJ', '', '(空)'),
(88, 'CK', '', '(空)'),
(89, 'CL', '', '(空)'),
(90, 'CM', '', '(空)'),
(91, 'CN', '', '(空)'),
(92, 'CO', '', '(空)'),
(93, 'CP', '', '(空)'),
(94, 'CQ', '', '(空)'),
(95, 'CR', '', '(空)'),
(96, 'CS', '', '(空)'),
(97, 'CT', '', '(空)'),
(98, 'CU', '', '(空)'),
(99, 'CV', 'bldg_site_ja_jp', '公式ホームページ'),
(100, 'CW', '', '(空)'),
(101, 'CX', '', '(空)'),
(102, 'CY', '', '(空)'),
(103, 'CZ', '', '(空)'),
(104, 'DA', '', '(空)'),
(105, 'DB', '', '(空)'),
(106, 'DC', 'address_en_us', 'Address'),
(107, 'DD', 'completion_en_us', 'Completion'),
(108, 'DE', 'extension_en_us', 'Extension'),
(109, 'DF', 'renovation_en_us', 'Renovation'),
(110, 'DG', 'floors_en_us', 'Number of|&floors'),
(111, 'DH', 'structure_en_us', 'Structure'),
(112, 'DI', 'gross_area_en_us', 'Gross area'),
(113, 'DJ', 'net_area_en_us', 'Net area'),
(114, 'DK', 'site_area_en_us', 'Site area'),
(115, 'DL', 'bldg_height_en_us', 'Building height'),
(116, 'DM', 'architect_en_us', 'Architect'),
(117, 'DN', 'elevators_en_us', 'Elevators'),
(118, 'DO', 'hvac_system_en_us', 'HVAC system'),
(119, 'DP', 'hvac_office_en_us', 'Standard HVAC|&hours (office)'),
(120, 'DQ', 'hvac_retail_en_us', 'Standard HVAC|&hours (retail)'),
(121, 'DR', 'refresh_space_en_us', 'Refreshment|&space'),
(122, 'DS', 'com_infra_en_us', 'Communication|&infrastructure'),
(123, 'DT', 'open_hours_en_us', 'Open hours'),
(124, 'DU', 'security_system_en_us', 'Security system'),
(125, 'DV', 'after_hours_access_en_us', 'After hours access'),
(126, 'DW', '', '(空)'),
(127, 'DX', 'parking_space_en_us', 'Parking space'),
(128, 'DY', 'parking_open_en_us', 'Parking open hours'),
(129, 'DZ', 'comments_en_us', 'Comments'),
(130, 'EA', '', '(空)'),
(131, 'EB', '', '(空)'),
(132, 'EC', '', '(空)'),
(133, 'ED', '', '(空)'),
(134, 'EE', '', '(空)'),
(135, 'EF', '', '(空)'),
(136, 'EG', '', '(空)'),
(137, 'EH', '', '(空)'),
(138, 'EI', '', '(空)'),
(139, 'EJ', '', '(空)'),
(140, 'EK', '', '(空)'),
(141, 'EL', '', '(空)'),
(142, 'EM', '', '(空)'),
(143, 'EN', '', '(空)'),
(144, 'EO', '', '(空)'),
(145, 'EP', '', '(空)'),
(146, 'EQ', 'floor_area_en_us', 'Typical floor area'),
(147, 'ER', 'floor_load_en_us', 'Floor load'),
(148, 'ES', 'ceiling_height_en_us', 'Floor-to-ceiling'),
(149, 'ET', 'outlet_capacity_en_us', 'Electric (outlet)|&capacity'),
(150, 'EU', 'raised_floor_en_us', 'raised floor'),
(151, 'EV', 'bathroom_en_us', 'Bathroom'),
(152, 'EW', 'pantry_en_us', 'Pantry'),
(153, 'EX', '', '(空)'),
(154, 'EY', '', '(空)'),
(155, 'EZ', '', '(空)'),
(156, 'FA', '', '(空)'),
(157, 'FB', '', '(空)'),
(158, 'FC', '', '(空)'),
(159, 'FD', '', '(空)'),
(160, 'FE', '', '(空)'),
(161, 'FF', '', '(空)'),
(162, 'FG', '', '(空)'),
(163, 'FH', '', '(空)'),
(164, 'FI', '', '(空)'),
(165, 'FJ', '', '(空)'),
(166, 'FK', 'bldg_site_en_us', 'Bldg. site'),
(167, 'FL', '', '(空)'),
(168, 'FM', '', '(空)'),
(169, 'FN', '', '(空)'),
(170, 'FO', '', '(空)'),
(171, 'FP', '', '(空)'),
(172, 'FQ', '', '(空)'),
(173, 'FR', '', '(空)'),
(174, 'FS', '', '(空)'),
(175, 'FT', '', '認証取得済み'),
(176, 'FU', '', '再エネ導入ビル'),
(177, 'FV', '', '取得済み認証'),
(178, 'FW', '', 'テナント専用ラウンジ'),
(179, 'FX', '', '防災センター番号'),
(180, 'FY', '', 'オフィスサポート施設'),
(181, 'FZ', 'nearest_station_ja_jp', '最　寄　駅'),
(182, 'GA', 'nearest_station_en_us', 'Nearest Station');

-- EOL
