--
-- CMS1
--   Transaction Tables
--     Building
--

use cms1;

--
-- ビルディング
--
DROP TABLE IF EXISTS `t_building`;
CREATE TABLE `t_building` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ビルディングID',
    -- begin CSVからの情報
    `bldg_code`                TEXT COMMENT 'ビルコード',
    `name_ja_jp`               TEXT COMMENT 'ビル名',
    `name_en_us`               TEXT COMMENT 'ビル名(英語)',
    `name_kana`                TEXT COMMENT 'ビル名(カナ)',
    `area_code`                TEXT COMMENT 'オフィスビル一覧用エリアコード',
    `bldg_kubun`               TEXT COMMENT '新ビル区分',
    `pref_ja_jp`               TEXT COMMENT '都道府県名',
    `loca_ja_jp`               TEXT COMMENT '所在地',
    `pref_en_us`               TEXT COMMENT '都道府県名(英語)',
    `loca_en_us`               TEXT COMMENT '所在地(英語)',
    `srch_ward`                TEXT COMMENT '検索用エリア(区)',
    `srch_area`                TEXT COMMENT '検索用エリア(オフィスエリア)',
    `use_route`                TEXT COMMENT '利用可能路線',
    `acc01_ja_jp`              TEXT COMMENT 'アクセス01',
    `acc02_ja_jp`              TEXT COMMENT 'アクセス02',
    `acc03_ja_jp`              TEXT COMMENT 'アクセス03',
    `acc04_ja_jp`              TEXT COMMENT 'アクセス04',
    `acc05_ja_jp`              TEXT COMMENT 'アクセス05',
    `acc06_ja_jp`              TEXT COMMENT 'アクセス06',
    `acc01_en_us`              TEXT COMMENT 'アクセス(英語)01',
    `acc02_en_us`              TEXT COMMENT 'アクセス(英語)02',
    `acc03_en_us`              TEXT COMMENT 'アクセス(英語)03',
    `acc04_en_us`              TEXT COMMENT 'アクセス(英語)04',
    `acc05_en_us`              TEXT COMMENT 'アクセス(英語)05',
    `acc06_en_us`              TEXT COMMENT 'アクセス(英語)06',
    `appeal_ja_jp`             TEXT COMMENT 'アピール',
    `appeal_en_us`             TEXT COMMENT 'アピール(英語)',
    `dep_ja_jp`                TEXT COMMENT '担当部署名',
    `dep_en_us`                TEXT COMMENT '担当部署名(英語)',
    `person_ja_jp`             TEXT COMMENT '担当者名',
    `person_en_us`             TEXT COMMENT '担当者名(英語)',
    `person_tel`               TEXT COMMENT '担当者電話番号',
    `person_email`             TEXT COMMENT '担当者メールアドレス',
    `rain`                     TEXT COMMENT '雨に濡れない',
    `scale_ja_jp`              TEXT COMMENT '建物規模',
    `scale_en_us`              TEXT COMMENT '建物規模(英語)',
    `address_ja_jp`            TEXT COMMENT '所在地',
    `completion_ja_jp`         TEXT COMMENT '竣工年月',
    `extension_ja_jp`          TEXT COMMENT '増築年月',
    `renovation_ja_jp`         TEXT COMMENT '最新リニューアル完了年月',
    `floors_ja_jp`             TEXT COMMENT '規模',
    `structure_ja_jp`          TEXT COMMENT '構造',
    `gross_area_ja_jp`         TEXT COMMENT '延床面積',
    `net_area_ja_jp`           TEXT COMMENT '有効面積',
    `site_area_ja_jp`          TEXT COMMENT '敷地面積',
    `bldg_height_ja_jp`        TEXT COMMENT '建物高さ',
    `architect_ja_jp`          TEXT COMMENT '設計監理',
    `elevators_ja_jp`          TEXT COMMENT 'エレベーター',
    `hvac_system_ja_jp`        TEXT COMMENT '空調設備',
    `hvac_office_ja_jp`        TEXT COMMENT '基準冷暖房供給|&時間（事務所）',
    `hvac_retail_ja_jp`        TEXT COMMENT '基準冷暖房供給|&時間（店舗）',
    `com_infra_ja_jp`          TEXT COMMENT '通信インフラ',
    `office_lobby`             TEXT COMMENT 'オフィスロビー',
    `emergency_power`          TEXT COMMENT '停電時のテナント専用部電力供給',
    `open_hours_ja_jp`         TEXT COMMENT '開閉館時間',
    `dining_facilities`        TEXT COMMENT '飲食施設充実',
    `vip_correspondense`       TEXT COMMENT 'VIP対応',
    `management_form`          TEXT COMMENT '管理形態',
    `security_system_ja_jp`    TEXT COMMENT '夜間入退館方法',
    `refresh_space_ja_jp`      TEXT COMMENT 'リフレッシュコーナー',
    `parking_space_ja_jp`      TEXT COMMENT 'ガレージ収容台数',
    `parking_open_ja_jp`       TEXT COMMENT 'ガレージ営業時間',
    `comments_ja_jp`           TEXT COMMENT '特記事項',
    `floor_area_ja_jp`         TEXT COMMENT '床面積',
    `floor_load_ja_jp`         TEXT COMMENT '床荷重',
    `small_area`               TEXT COMMENT '小規模面積あり',
    `ceiling_height_ja_jp`     TEXT COMMENT '天井高',
    `outlet_capacity_ja_jp`    TEXT COMMENT 'コンセント容量',
    `raised_floor_ja_jp`       TEXT COMMENT 'ＯＡフロア',
    `bathroom_ja_jp`           TEXT COMMENT 'トイレ',
    `pantry_ja_jp`             TEXT COMMENT '給湯室',
    `bldg_site_ja_jp`          TEXT COMMENT '公式ホームページ',
    `address_en_us`            TEXT COMMENT 'Address',
    `completion_en_us`         TEXT COMMENT 'Completion',
    `extension_en_us`          TEXT COMMENT 'Extension',
    `renovation_en_us`         TEXT COMMENT 'Renovation',
    `floors_en_us`             TEXT COMMENT 'Number of|&floors',
    `structure_en_us`          TEXT COMMENT 'Structure',
    `gross_area_en_us`         TEXT COMMENT 'Gross area',
    `net_area_en_us`           TEXT COMMENT 'Net area',
    `site_area_en_us`          TEXT COMMENT 'Site area',
    `bldg_height_en_us`        TEXT COMMENT 'Building height',
    `architect_en_us`          TEXT COMMENT 'Architect',
    `elevators_en_us`          TEXT COMMENT 'Elevators',
    `hvac_system_en_us`        TEXT COMMENT 'HVAC system',
    `hvac_office_en_us`        TEXT COMMENT 'Standard HVAC|&hours (office)',
    `hvac_retail_en_us`        TEXT COMMENT 'Standard HVAC|&hours (retail)',
    `refresh_space_en_us`      TEXT COMMENT 'Refreshment|&space',
    `com_infra_en_us`          TEXT COMMENT 'Communication|&infrastructure',
    `open_hours_en_us`         TEXT COMMENT 'Open hours',
    `security_system_en_us`    TEXT COMMENT 'Security system',
    `after_hours_access_en_us` TEXT COMMENT 'After hours access',
    `parking_space_en_us`      TEXT COMMENT 'Parking space',
    `parking_open_en_us`       TEXT COMMENT 'Parking open hours',
    `comments_en_us`           TEXT COMMENT 'Comments',
    `floor_area_en_us`         TEXT COMMENT 'Typical floor area',
    `floor_load_en_us`         TEXT COMMENT 'Floor load',
    `ceiling_height_en_us`     TEXT COMMENT 'Floor-to-ceiling',
    `outlet_capacity_en_us`    TEXT COMMENT 'Electric (outlet)|&capacity',
    `raised_floor_en_us`       TEXT COMMENT 'Raised floor',
    `bathroom_en_us`           TEXT COMMENT 'Bathroom',
    `pantry_en_us`             TEXT COMMENT 'Pantry',
    `bldg_site_en_us`          TEXT COMMENT 'Bldg. site',
    `certified`                TEXT COMMENT '認証取得済み',
    `renewable_energy`         TEXT COMMENT '再エネ導入ビル',
    `certification_ja_jp`      TEXT COMMENT '取得済み認証',
    `tenant_lounge`            TEXT COMMENT 'テナント専用ラウンジ',
    `safety_center_tel`        TEXT COMMENT '防災センター番号',
    `office_support_ja_jp`     TEXT COMMENT 'オフィスサポート施設',
    `nearest_station_ja_jp`    TEXT COMMENT '最寄駅',
    `nearest_station_en_us`    TEXT COMMENT 'Nearest Station',
    -- end CSVからの情報
    -- begin WEB管理画面で追加する情報
    `display_ja_jp`            TEXT COMMENT 'ビル表示名',
    `display_en_us`            TEXT COMMENT 'ビル表示名(英語)',
    `abrev_ja_jp`              TEXT COMMENT 'ビル略称名',
    `abrev_en_us`              TEXT COMMENT 'ビル略称名(英語)',
    `introd_ja_jp`             TEXT COMMENT 'ビル紹介文',
    `introd_en_us`             TEXT COMMENT 'ビル紹介文(英語)',
    `focus`                    INT  COMMENT '注力物件',
    `keyword`                  TEXT COMMENT '検索キーワード',
    `facility_caption_ja_jp`   TEXT COMMENT '商業施設画像キャプション',
    `facility_caption_en_us`   TEXT COMMENT '商業施設画像キャプション(英語)',
    `longitude`                TEXT COMMENT '緯度',
    `latitude`                 TEXT COMMENT '経度',
    `street_view_url`          TEXT COMMENT 'GoogleストリートビューURL',
    `street_view_tag`          TEXT COMMENT 'Googleストリートビュー埋込タグ',
    `office_info_site`         INT  COMMENT 'オフィス情報サイト表示フラグ',
    `similar`                  TEXT COMMENT '類似物件', -- Pending
 -- `similar01_area`           INT  COMMENT '類似物件01エリア',
 -- `similar01_name`           TEXT COMMENT '類似物件01物件',
 -- `similar02_area`           INT  COMMENT '類似物件02エリア',
 -- `similar02_name`           TEXT COMMENT '類似物件02物件',
 -- `similar03_area`           INT  COMMENT '類似物件03エリア',
 -- `similar03_name`           TEXT COMMENT '類似物件03物件',
 -- `similar04_area`           INT  COMMENT '類似物件04エリア',
 -- `similar04_name`           TEXT COMMENT '類似物件04物件',
 -- `similar05_area`           INT  COMMENT '類似物件05エリア',
 -- `similar05_name`           TEXT COMMENT '類似物件05物件',
 -- `similar06_area`           INT  COMMENT '類似物件06エリア',
 -- `similar06_name`           TEXT COMMENT '類似物件06物件',
 -- `similar07_area`           INT  COMMENT '類似物件07エリア',
 -- `similar07_name`           TEXT COMMENT '類似物件07物件',
 -- `similar08_area`           INT  COMMENT '類似物件08エリア',
 -- `similar08_name`           TEXT COMMENT '類似物件08物件',
 -- `similar09_area`           INT  COMMENT '類似物件09エリア',
 -- `similar09_name`           TEXT COMMENT '類似物件09物件',
 -- `unregistered`             INT  COMMENT '追加情報未登録',
    -- end WEB管理画面で追加する情報
    `del_flg` BOOLEAN   NOT NULL COMMENT '削除フラグ',
    `c_ts`    TIMESTAMP NOT NULL COMMENT '作成日時',
    `c_id`    BIGINT    NOT NULL COMMENT '作成者構成員ID',
    `c_ip`    TEXT      NOT NULL COMMENT '作成者IP-Address',
    `u_ts`    TIMESTAMP          COMMENT '更新日時',
    `u_id`    BIGINT             COMMENT '更新者構成員ID',
    `u_ip`    TEXT               COMMENT '更新者IP-Address',
    PRIMARY KEY (id)
) ENGINE=InnoDB COMMENT 'ビルディング';

--
-- ビルディング画像情報
--
DROP TABLE IF EXISTS `t_bldg_image`;
CREATE TABLE `t_bldg_image` (
    `id`             BIGINT NOT NULL AUTO_INCREMENT COMMENT '画像情報ID',
    `bldg_id`        BIGINT                         COMMENT 'ビルディングID',
    `bldg_img_attr`  INT                            COMMENT '画像属性ID',
    `seq`            INT                            COMMENT '表示順',
    `file_name`      TEXT                           COMMENT 'ファイル名',
    `caption`        TEXT                           COMMENT 'キャプション',
    `url`            TEXT                           COMMENT 'アイコンURL',
    `use_flg`        BOOLEAN   NOT NULL             COMMENT '使用フラグ',
    `c_ts`           TIMESTAMP NOT NULL             COMMENT '作成日時',
    `c_id`           BIGINT    NOT NULL             COMMENT '作成者構成員ID',
    `c_ip`           TEXT      NOT NULL             COMMENT '作成者IP-Address',
    `u_ts`           TIMESTAMP                      COMMENT '更新日時',
    `u_id`           BIGINT                         COMMENT '更新者構成員ID',
    `u_ip`           TEXT                           COMMENT '更新者IP-Address',
    PRIMARY KEY (id)
) ENGINE=InnoDB COMMENT 'ビルディング画像情報';

-- EOL
